version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: etldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d etldb"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build: ./etl
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: etldb
    depends_on:
      database:
        condition: service_healthy
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge

volumes:
  postgres_data: